### ISSUE TITLE
SSL support 

### ISSUE THREAD

**Issue by pragmaticivan** [eea/eea.docker.jenkins#4]
Hi there, thanks for the really nice project.

Is there a "easy" way to enable ssl for the jenkins master? Would be good it appears on the documentation.

**Comment by avoinea** [comment]
@pragmaticivan I think you'll need jenkins behind apache or nginx. This may help http://serverfault.com/questions/278555/how-to-use-jenkins-with-ssl-https

**Comment by avoinea** [comment]
Now I see what you mean: According to https://wiki.wocommunity.org/display/documentation/Installing+and+Configuring+Jenkins the `jenkins-master` CMD should be something like:

```
java -jar jenkins.war --httpPort=-1 --httpsPort=8080 --httpsKeyStore=keystore.jks --httpsKeyStorePassword=ToPSecRet321
```

**Comment by avoinea** [comment]
And yes, that's supported by [jenkins base image](https://hub.docker.com/_/jenkins/) via `JENKINS_OPTS` environment variable, therefore also supported by this image.

I'm going to update README on this github repo and also on [eeacms/jenkins-master](https://hub.docker.com/r/eeacms/jenkins-master/) image.
